services:
  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - homelab-net

  twingate-connector-s:
    image: docker.io/twingate/connector:latest
    container_name: twingate-connector-s
    restart: unless-stopped
    network_mode: host
    environment:
      - TWINGATE_NETWORK=${TWINGATE_NETWORK_S}
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN_S}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN_S}

  twingate-connector-hl:
    image: docker.io/twingate/connector:latest
    container_name: twingate-connector-hl
    restart: unless-stopped
    environment:
      - TWINGATE_NETWORK=${TWINGATE_NETWORK_HL}
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN_HL}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN_HL}
    networks:
      - homelab-net

  vaultwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
    volumes:
      - vaultwarden_data:/data
    networks:
      - homelab-net

networks:
  homelab-net:
    external: true

# Déclarez le volume géré en bas de fichier
volumes:
  vaultwarden_data:
